/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/assets/models/ufo.glb --transform 
Files: src/assets/models/ufo.glb [2.7MB] > ufo-transformed.glb [291.24KB] (89%)
Author: blazej.mikula (https://sketchfab.com/blazej.mikula)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-4612099c7bc14e9c9d20f486aa9a50db
Title: UFO
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function UFOModel(props) {
  const { nodes, materials } = useGLTF('/ufo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Material_012-material'].geometry} material={materials['Material.012']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Material_007-material'].geometry} material={materials['Material.007']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Material_009-material'].geometry} material={materials['Material.009']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Material_008-material'].geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Material_013-material'].geometry} material={materials['Material.013']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ufo-transformed.glb')
